### ISSUE TITLE
coquille : commentaire algorithme du backfitting

### ISSUE THREAD

**Issue by code-instable** [allemand-instable/ENSAI-2A-stage-FGAM#1]
**page :** 6

dans l'algorithme du backfitting le commentaire

"m[r−1]_k : vient juste d’être estimée"

devrait être : "m[**r**]_k : vient juste d’être estimée"

![image](https://github.com/allemand-instable/ENSAI-2A-stage-FGAM/assets/68656923/a5a0c15b-403e-403b-a395-72ffcd8b2f0f)

**Comment by allemand-instable** [comment]
fixed in [commit 354759b](https://github.com/allemand-instable/ENSAI-2A-stage-FGAM/commit/354759b93fc45eeba1bac5a88498810f2fb35f29)

**Comment by code-instable** [comment]
fixed in [commit 354759b](https://github.com/allemand-instable/ENSAI-2A-stage-FGAM/commit/354759b93fc45eeba1bac5a88498810f2fb35f29)
